### ISSUE TITLE
PVTv2: The conflict between the paper and the code

### ISSUE THREAD

**Issue by LeKiet258** [ESandML/FCBFormer#2]
Hi, I have searched and found no relevant results.
I printed the architecture of class TB (Models/models.py) and found that in _get\_pyramid()_ method, the _pyramid[]_ list consisted only 3 feature maps F1, F2, F3 (since the append happens 3 times) instead of 4 feature maps as proposed in your paper. Also, it seems like self.backbone[10] is, I guess, the missing F4. Therefore, there are actually 3 emphasized feature maps after the LE module. This affects the _forward()_ method, i.e. at the first concat step of SFA, instead of concatenating F4_emph & F3_emph as in the paper, F3_emph & F3_emph are concatenated and that's weird.
Is my understanding correct? If so, why isn't F4 used? 
Thank you very much!

![issue_1](https://user-images.githubusercontent.com/70853278/199409825-06b5765e-3d6f-4727-9a4d-8d528731cd5b.png)
![forward fn](https://user-images.githubusercontent.com/70853278/199410719-5801506b-2e83-4628-aaad-c7e0234dd039.png)

PS: I have read the [PVT repo](https://github.com/whai362/PVT) of whai362 and in class PyramidVisionTransformer, F4 is not used by default but I don't understand why

**Comment by ESandML** [comment]
Hi Lê Kiệt, thanks for checking out our work!

Unfortunately, I really can't understand why you are experiencing only 3 feature tensors in the _pyramid[]_ list. The following shows that you should end up with 4:

![image](https://user-images.githubusercontent.com/111010889/199469914-066c2cb7-46b0-4233-9677-da1c08910d76.png)

The append within the _get_pyramid()_ function should occur 4 times, since there are 12 modules within the backone:

![image](https://user-images.githubusercontent.com/111010889/199467094-f2459427-226c-48a0-8e70-98bde62d936f.png)

This means that the for loop in _get_pyramid()_ runs for i=0 to i=11 (not i=10), and F4 is appended when i=11.

This also means that, in the _forward()_ function, _pyramid_emph[-1]=pyramid_emph[3]_ (not _pyramid_emph[-1]=pyramid_emph[2]_), so that F4_emph and F3_emph are concatenated on the first iteration of the loop (not F3_emph with itself).

I have tried to reproduce your issue with different input sizes but either ended up with 4 feature tensors or an error, so please let me know if you figure out the cause.

**Comment by LeKiet258** [comment]
Thank you for your fast reply. I checked my code and found that when I printed, in Models/pvt_v2.py, I commented the `self.head` in class PyramidVisionTransformerV2's constructor as highlighted in the image and also the line `x = self.head(x)` in the _forward()_ method of the same class because I misunderstood and thought it was some kind of unnamed layer between the feature maps produced by PVT and the LE module but turned out it wasn't. When I uncommented `self.head`, I got the result of 4 feature maps with the right shapes as yours.

![issue_1](https://user-images.githubusercontent.com/70853278/199494584-ac728e15-6f6d-4096-a5dd-6ddb814bdf6b.png)

However, I still have doubt about the purpose of `self.head`, I guess it was not F4 since every feature map in PVT is produced after the LayerNorm. Also, what does `num_classes=1000` means as an argument in class PyramidVisionTransformerV2's constructor and in `nn.Linear()`?

**Comment by ESandML** [comment]
No problem at all. Thank you very much for clarifying the cause.

`self.head` is the classification head (a linear layer), which is included in the original PVTv2 model for training on ImageNet, hence the `num_classes=1000` (1000 classes in ImageNet). The weight file we load for the backbone in TB (Models/models.py line 125) contains the weights for the fully trained ImageNet classifier, including `self.head`. Therefore, we have to first build the model with `self.head` included, so that the weights can be loaded in. Since we do not need this classification head in FCBFormer, we then throw away `self.head` by excluding it from `self.backbone` using `[:-1]` (Models/models.py line 126).

Hope this helps! Let me know if you have any further questions.

**Comment by LeKiet258** [comment]
Thanks! Your detailed answer clarifies my doubt a lot!
